language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
    include:
        - os: osx
          env: OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include" OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
          rust: stable
        - os: osx
          env: OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include" OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
          rust: beta
        - os: osx
          env: OPENSSL_INCLUDE_DIR="$(brew --prefix openssl)/include" OPENSSL_LIB_DIR="$(brew --prefix openssl)/lib"
          rust: nightly
