language: rust
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx

before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH

script:
    - |
        travis-cargo build &&
        travis-cargo test &&
        TRAVIS_CARGO_NIGHTLY_FEATURE="" travis-cargo test -- --no-default-features --features "ssl with_serde"
