language: rust
rust:
    - stable
    - beta
    - nightly

os:
    - osx
    - linux

env:
    - OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include
    - OPENSSL_LIB_DIR=`brew --prefix openssl`/lib
