language: rust
rust:
    - stable
    - beta
    - nightly

matrix:
    include:
        - os: osx
          env: OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install openssl; fi
