language: rust
rust:
    - stable
    - beta
    - nightly
os:
    - linux
    - osx

before_script:
    - |
        pip install 'travis-cargo<0.2' --user &&
        export PATH=$HOME/.local/bin:$PATH &&
        export PATH=$HOME/Library/Python/$(python -V 2>&1 | cut -d' ' -f2)/bin:$PATH &&
        export TRAVIS_CARGO_NIGHTLY_FEATURE=""

script:
    - |
        travis-cargo build &&
        travis-cargo test &&
        travis-cargo test -- --no-default-features --features "ssl with_serde"
