[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Rust HTTP client API styled after awesome Python requests - [WORK IN PROGRESS]"
keywords = ["http", "client", "python", "requests"]
license = "MIT"
name = "requests"
repository = "https://github.com/imp/requests-rs.git"
version = "0.0.5"

[dependencies]
hyper = "0.8.0"
serde = "0.7.0"
serde_json = "0.7.0"
serde_macros = "0.7.2"

[dependencies.clippy]
optional = true
version = "0.0.63"

[features]
default = []
