[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Rust HTTP client library styled after awesome Python requests - [WORK IN PROGRESS]"
license = "MIT"
name = "requests"
repository = "https://github.com/imp/requests-rs.git"
version = "0.0.0"

[dependencies]
hyper = "0.7.2"
