[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Rust HTTP client API styled after awesome Python requests - [WORK IN PROGRESS]"
keywords = ["http", "client", "python", "requests"]
license = "MIT"
name = "requests"
repository = "https://github.com/imp/requests-rs.git"
version = "0.0.4"

[dependencies]
hyper = "0.8.0"
