[package]
authors = ["Cyril Plisko <cyril.plisko@mountall.com>"]
description = "Rust HTTP client API styled after awesome Python requests - [WORK IN PROGRESS]"
keywords = ["http", "rest", "client", "python", "requests"]
license = "MIT"
name = "requests"
repository = "https://github.com/imp/requests-rs.git"
homepage = "https://github.com/imp/requests-rs"
version = "0.0.13"

[dependencies]
json = "0.4"

[dependencies.hyper]
version = "0.9"
default-features = false

[features]
default = ["ssl"]
ssl = ["hyper/ssl"]
